### ISSUE TITLE
Ревью React версии тестового задания

### ISSUE THREAD

**Issue by akuznetsov-md** [blotteracid/mercdev-test#1]
Разработка приложений на React отличается от привычного создания сайтов с помощью HTML, CSS и JS.

В привычном подходе у нас есть структура сайта, описанная при помощи HTML. Есть CSS, который делает сайт красивым. И есть JS, который делает сайт "динамичным". При таком подходе HTML, CSS и JS явно никак не связаны друг с другом. Мы только знаем, что и относятся к одному и тому же сайту.

```
HTML
- лэйаут страницы
- лэйаут формы авторизации
- лэйаут профиля пользователя

CSS
- стили страницы
- стили формы авторизации
- стили профиля пользователя

JS
- функции базовые
- функции формы авторизации
- функции профиля пользователя
```

Разработка приложений на React строится на компонентном подходе. Ключевое отличие компонентного подхода в том, что мы разделяем приложение на самостоятельные элементы интерфейса, исходя из их предназначения:

```
Корневой компонент
- лэйаут страницы
- стили страницы
- функции базовые

Компонент формы авторизации
- лэйаут формы авторизации
- стили формы авторизации
- функции формы авторизации

Компонент профиля пользователя
- лэйаут профиля пользователя
- стили профиля пользователя
- функции профиля пользователя
```

Попробуй поправить свой код так, чтобы он удовлетворял компонентному подходу. Но прежде чем исправлять, напиши, что именно ты собираешься изменить.

**Comment by blotteracid** [comment]
1) Создать корневой компонент с базовой разметкой и стилями (там будет фон, импорт лого и импорт формы);
2) Создать компонент профиля пользователя (у меня сейчас его нет вообще) с аватаркой и тайтлом;
3) В соответствии с первыми двумя пунктами поправить компонент формы;
4) Создать папки под компоненты и перенести в них код самого компонента и стили для него.

P.S: как вообще сам код?

**Comment by akuznetsov-md** [comment]
Ок. Жду правок в виде PR (Pull Request).

> P.S: как вообще сам код?

С кодом можно работать :)

**Comment by blotteracid** [comment]
@akuznetsov-md https://github.com/blotteracid/mercdev-test/pulls
PR готов
